### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by binhussen** [binhussen/capstone-js#21]
### Project Link [https://github.com/binhussen/capstone-js/projects/1](https://github.com/binhussen/capstone-js/projects/1)
Team Members
- @AbelG101 Student A
- @binhussen Student B

**Comment by mwanawabangona** [comment]
Hi @binhussen n @AbelG101 

Your project is complete!  There is nothing else to say other than... good luck with the capstone :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights

*   Good job getting approved on your first try!! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
