### ISSUE TITLE
Morning Session Day 2 - Code Review

### ISSUE THREAD

**Issue by uisendy** [binhussen/capstone-js#30]
Good Work so far @binhussen and @AbelG101. 

✔️ Good GitFlow
✔️ Good HTML and CSS practises
✔️ Good Javascript best Practices
✔️ Good Interface and Use of API

I understand you are still at the wireframe part of the project for now, But we suggest you put up a like button animation to show that the likes counter increases. 

Again, the work so far is amazing and Awesome. 🚀 🚀 🚀

**Comment by binhussen** [comment]
Thank you @uisendy and @samlorlah for your feedback, we have updated the changes as requested and made the fixes we discussed Link [here](https://github.com/binhussen/foodie/)
