### ISSUE TITLE
Peer-to-peer Programming - Review

### ISSUE THREAD

**Issue by samlorlah** [binhussen/capstone-js#40]
<img src="https://media0.giphy.com/media/nbvFVPiEiJH6JOGIok/giphy.gif"/>

### Good job so far.

We must commend the level of hard work and professionalism in this job.

**Please work on the listed issue(s) below:**

- Prevent submission of empty data in the comment form.

**Comment by binhussen** [comment]
Thank you @uisendy and @samlorlah for your feedback, we have updated the changes as requested and made the fixes we discussed Link [here](https://github.com/binhussen/foodie/)
